import type { PortfolioItem, Testimonial, TimeSlot } from '@/types'

export const portfolioItems: PortfolioItem[] = [
  {
    id: '1',
    src: 'https://picsum.photos/seed/ink-geo-01/600/800',
    width: 600,
    height: 800,
    category: 'Geométrico',
    title: 'Mandala Geométrica',
    description: 'Composição geométrica de alta precisão com elementos mandálicos.',
  },
  {
    id: '2',
    src: 'https://picsum.photos/seed/ink-black-02/600/900',
    width: 600,
    height: 900,
    category: 'Blackwork',
    title: 'Dragão Blackwork',
    description: 'Dragão oriental em blackwork com sombras densas e linhas finas.',
  },
  {
    id: '3',
    src: 'https://picsum.photos/seed/ink-mini-03/600/600',
    width: 600,
    height: 600,
    category: 'Minimalista',
    title: 'Lua Fina',
    description: 'Crescente lunar minimalista com trabalho de linha ultra fina.',
  },
  {
    id: '4',
    src: 'https://picsum.photos/seed/ink-real-04/600/750',
    width: 600,
    height: 750,
    category: 'Realismo',
    title: 'Retrato em Realismo',
    description: 'Realismo fotográfico em preto e cinza com degradê impecável.',
  },
  {
    id: '5',
    src: 'https://picsum.photos/seed/ink-ori-05/600/850',
    width: 600,
    height: 850,
    category: 'Oriental',
    title: 'Carpa Koi',
    description: 'Carpa Koi tradicional japonesa com flores de cerejeira.',
  },
  {
    id: '6',
    src: 'https://picsum.photos/seed/ink-mini-06/600/650',
    width: 600,
    height: 650,
    category: 'Minimalista',
    title: 'Constelação',
    description: 'Constelação de Órion em pontos finos com linha delicada.',
  },
  {
    id: '7',
    src: 'https://picsum.photos/seed/ink-black-07/600/950',
    width: 600,
    height: 950,
    category: 'Blackwork',
    title: 'Floresta Sombria',
    description: 'Paisagem de pinheiros em blackwork cobrindo o antebraço.',
  },
  {
    id: '8',
    src: 'https://picsum.photos/seed/ink-geo-08/600/700',
    width: 600,
    height: 700,
    category: 'Geométrico',
    title: 'Olho de Hórus',
    description: 'Olho sagrado com geometria sagrada e proporção áurea.',
  },
  {
    id: '9',
    src: 'https://picsum.photos/seed/ink-real-09/600/800',
    width: 600,
    height: 800,
    category: 'Realismo',
    title: 'Leão Realista',
    description: 'Leão em realismo P&B com pelagem detalhada e expressão vigorosa.',
  },
  {
    id: '10',
    src: 'https://picsum.photos/seed/ink-ori-10/600/750',
    width: 600,
    height: 750,
    category: 'Oriental',
    title: 'Máscara Oni',
    description: 'Máscara Oni tradicional com chamas e composição densa.',
  },
  {
    id: '11',
    src: 'https://picsum.photos/seed/ink-mini-11/600/600',
    width: 600,
    height: 600,
    category: 'Minimalista',
    title: 'Flecha',
    description: 'Flecha minimalista com coordenadas geográficas em fonte fina.',
  },
  {
    id: '12',
    src: 'https://picsum.photos/seed/ink-geo-12/600/880',
    width: 600,
    height: 880,
    category: 'Geométrico',
    title: 'Lobo Geométrico',
    description: 'Lobo decomposto em facetas geométricas com linhas precisas.',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Marina Costa',
    avatar: 'https://picsum.photos/seed/avatar-mc/80/80',
    rating: 5,
    text: 'Simplesmente incrível. A Duda entendeu exatamente o que eu queria — um realismo que parecesse pintura. Fui com uma referência vaga e ela transformou em arte pura. A atenção ao detalhe é absurda, cada sombra no lugar certo. Já indiquei para toda minha família.',
    style: 'Realismo',
    date: 'Março 2025',
  },
  {
    id: '2',
    name: 'Lucas Ferreira',
    avatar: 'https://picsum.photos/seed/avatar-lf/80/80',
    rating: 5,
    text: 'Fiz um blackwork de manga completa e ficou a obra de arte que eu sempre sonhei. O traço da Duda é único — linhas firmes, cobertura uniforme e uma composição que flui naturalmente com a anatomia do braço. Profissionalismo do início ao fim.',
    style: 'Blackwork',
    date: 'Fevereiro 2025',
  },
  {
    id: '3',
    name: 'Isabela Nogueira',
    avatar: 'https://picsum.photos/seed/avatar-in/80/80',
    rating: 5,
    text: 'Queria algo delicado e minimalista no pulso. A Duda trouxe sketches incríveis na consulta, respeitou meu estilo e o resultado superou minhas expectativas. A linha é tão fina que parece desenhada a lápis na pele. Studio impecável, espaço acolhedor.',
    style: 'Minimalista',
    date: 'Janeiro 2025',
  },
  {
    id: '4',
    name: 'Rafael Monteiro',
    avatar: 'https://picsum.photos/seed/avatar-rm/80/80',
    rating: 5,
    text: 'Minha tattoo oriental cobriu a costela inteira e foi a melhor decisão que tomei. A Duda domina a técnica oriental de um jeito que poucos artistas no Brasil dominam. A carpa koi ficou com profundidade de cor impressionante. Cicatrizou perfeitamente.',
    style: 'Oriental',
    date: 'Dezembro 2024',
  },
  {
    id: '5',
    name: 'Thais Albuquerque',
    avatar: 'https://picsum.photos/seed/avatar-ta/80/80',
    rating: 5,
    text: 'Era minha primeira tatuagem e estava com muito medo. A Duda me recebeu com calma, explicou cada etapa do processo e foi extremamente cuidadosa durante a sessão. O resultado geométrico no ombro ficou perfeito. Já marquei a segunda!',
    style: 'Geométrico',
    date: 'Novembro 2024',
  },
]

export const availableTimeSlots: TimeSlot[] = [
  { time: '09:00', available: true },
  { time: '10:00', available: false },
  { time: '11:00', available: true },
  { time: '12:00', available: false },
  { time: '13:00', available: true },
  { time: '14:00', available: true },
  { time: '15:00', available: false },
  { time: '16:00', available: true },
  { time: '17:00', available: true },
  { time: '18:00', available: false },
]

export const tattooStyles = [
  'Todos',
  'Minimalista',
  'Realismo',
  'Blackwork',
  'Geométrico',
  'Oriental',
] as const

export const socialLinks = {
  instagram: 'https://instagram.com/dudacampostattoo',
  whatsapp: 'https://wa.me/5511999999999',
  tiktok: 'https://tiktok.com/@dudacampostattoo',
}
